#!/bin/bash

import_module reactor

_reactor_tasks=(
    "clean"
    "resources"
    "build"
    "install"
    "push"
    "deploy"
)

_reactor_chain=(
    "build resources"
    "install build"
    "push install"
    "deploy push"
)

function initialize_deployable {
    initialize_reactor
}
