#!/bin/bash

__modules_imported=()

_script_map=()
__script_search_paths=()
__custom_dirs=()


__custom_dirs=("$(pwd)")

IFS=$':' _custom_path=($IGNITE_PATH)
unset IFS
__custom_dirs+=("${_custom_path[@]}")

__custom_dirs+=("$IGNITE_INSTALLATION")

IFS=$':' _path=($PATH)
unset IFS

__script_search_paths=("${__custom_dirs[@]}")
__script_search_paths+=("${_path[@]}")

function search_scripts {
    for p in "${__script_search_paths[@]}"; do
        if `ls $p/ignite_* &> /dev/null`; then
            for _match in `ls $p/ignite_*`; do
                if [[ "$_match" == "$p/ignite_" ]]; then
                    continue
                fi
                _prefix=$(echo "$p/ignite_" | sed 's/\//\\\//g')
                _name=$(echo $_match | sed s/$_prefix//g)
                _script_map+=("$_name $_match")
            done
        fi
    done
}

function resolve_script {
    for p in "${__script_search_paths[@]}"; do
        if [ -f "$p/ignite_$1" ] || [ -L "$p/ignite_$1" ]; then
            echo "$p/ignite_$1"
            return 0
        fi
    done
    return 1
}

function import_module {
    for visited in ${__modules_imported[@]}; do
        if [[ $1 == $visited ]]; then
            return
        fi
    done

    for dir in ${__custom_dirs[@]}; do
        if [ -f "$dir/modules/$1" ]; then
            . "$dir/modules/$1"
            __modules_imported+=("$1")
            return
        fi
    done

    echo "Could not find module $1 (check your \$IGNITE_PATH variable is set correctly and the module exists in the module/ subdirectory" >&2
    return 1
}
