#!/bin/bash

import_module colors

# TODO: Improve implementation

function __log {
    echo -en "$@${CLRT}"
}

function print_warning {
    __log "${YELLOW_FG}$@\n"
}

function print_error {
    __log "${RED_FG}$@\n"
}

function print_success {
    __log "${GREEN_FG}$@\n"
}

function print_info {
    __log "${CYAN_FG}$@\n"
}

function print_custom {
    __log $@
}
