#!/bin/bash

_puppet_module_location=${_puppet_module_location:-"."}
_puppet_module_output_dir=${_puppet_module_output_dir:-"pkg"}
_puppet_module_file=${_puppet_module_file}

import_module print

function puppet_module_build {
    pushd $_puppet_module_location > /dev/null
    print_info "Building puppet module"

    _puppet_module_validate

    bundle exec puppet module build --modulepath .
    if [ ! -f "$_puppet_module_output_dir/$_puppet_module_file" ]; then
        print_error "Module build reported successful, but build artifact does not exist"
        return 1
    fi
    print_success "Module build successful"
    popd > /dev/null
}

function puppet_module_validate {
    return
}
