#!/bin/bash

IGNITE_SEARCHBASE+=(
    "$(pwd)"
    "$IGNITE_INSTALLATION"
)

function _init_searchbase {
    _script_map=()
    _search_base=(${IGNITE_SEARCHBASE[@]})
    IFS=$':' _paths=($PATH)
    unset IFS

    _search_base+=("${_paths[@]}")
}

function search_scripts {
    _init_searchbase
    _script_map=()
    for p in "${_search_base[@]}"; do
        if `ls $p/ignite_* &> /dev/null`; then
            for _match in `ls $p/ignite_*`; do
                if [[ "$_match" == "$p/ignite_" ]]; then
                    continue
                fi
                _prefix=$(echo "$p/ignite_" | sed 's/\//\\\//g')
                _name=$(echo $_match | sed s/$_prefix//g)
                _script_map+=("$_name $_match")
            done
        fi
    done
}

function resolve_script {
    _init_searchbase
    for p in "${_search_base[@]}"; do
        if [ -f "$p/ignite_$1" ] || [ -L "$p/ignite_$1" ]; then
            echo "$p/ignite_$1"
            return 0
        fi
    done
    return 1
}
