#!/bin/bash

# TODO: This really needs a redo!

_complete_script_location=$(dirname $(readlink $_ || echo $_))
. "$_complete_script_location/_ignite_search"
. "$_complete_script_location/modules/import"
function _ignite_complete {
    COMPREPLY=()
    if [[ ${#COMP_WORDS[@]} -eq 1 ]] || [[ ${#COMP_WORDS[@]} -eq 2 ]] && [[ ${COMP_CWORD} -eq 1 ]]; then
        search_scripts
        for s in "${_script_map[@]}"; do
            s=($s)
            COMPREPLY+=("${s[0]}")
        done
    elif [[ ${#COMP_WORDS[@]} -eq 2 ]] || [[ ${#COMP_WORDS[@]} -eq 3 ]] && [[ ${COMP_CWORD} -eq 2 ]]; then
        _ignite_script_path=$(resolve_script ${COMP_WORDS[1]}) || {
            return
        }
        . "$_ignite_script_path"

        for v in "${VALID_OPERATIONS[@]}"; do
            v=($v)
            COMPREPLY+=("${v[0]}")
        done
    # else
    #     # COMPREPLY=("$(compgen -d)")
    fi
}

complete -F _ignite_complete -o default ignite
