#!/bin/bash

_puppet_module_location=${_puppet_module_location:-"."}
_puppet_module_output_dir=${_puppet_module_output_dir:-"pkg"}
_puppet_module_file=${_puppet_module_file}

function _puppet_module_build {
    pushd $_puppet_module_location > /dev/null
    log $CYAN_FG "Building puppet module"

    _puppet_module_validate

    bundle exec puppet module build --modulepath .
    if [ ! -f "$_puppet_module_output_dir/$_puppet_module_file" ]; then
        log $RED_FG "Module build reported successful, but build artifact does not exist"
        return 1
    fi
    log $GREEN_FG "Module build successful"
    popd > /dev/null
}

function _puppet_module_validate {
    return
}
