#!/bin/bash

# May need further improvements, see #1
_complete_script_location=$(dirname $(readlink $_ || echo $_))
function _ignite_complete {
    . "$_complete_script_location/modules/import"
    import_module commands
    COMPREPLY=()
    if [[ ${COMP_CWORD} -eq 1 ]]; then
        search_scripts
        for s in "${_script_map[@]}"; do
            s=($s)
            COMPREPLY+=("${s[0]}")
        done
    elif [[ ${COMP_CWORD} -eq 2 ]]; then
        _ignite_script_path=$(resolve_script ${COMP_WORDS[1]}) || {
            return
        }
        . "$_ignite_script_path"
        COMPREPLY+=(`_commands_get`)
    fi
}

complete -F _ignite_complete -o default ignite
