#!/bin/bash
set -e

################################################################################
# Behavoural
################################################################################

. _ignite_log
. _ignite_colors


function usage {
    if [[ "${#VALID_OPERATIONS[@]}" -eq 0 ]]; then
        echo "No operations defined in ignite script" >&2
        exit 1
    fi
    echo "Usage:"
    for op in "${VALID_OPERATIONS[@]}"; do
        echo -e "\t$0 $CONF_FILE $op"
    done
}

function main {
    if [[ $# -eq 0 ]] || [ -z "$1" ]; then
        usage
        exit 1
    fi
    base="$1"
    shift

    # See if implementation-defined operation
    for op in "${VALID_OPERATIONS[@]}"; do
        op=(${op[@]})
        if [[ "$base" == "${op[0]}" ]]; then
            if [ ! -d "$SOURCE_PATH" ]; then
                echo "$SOURCE_PATH does not exist" >&2
                exit 1
            fi
            cd $SOURCE_PATH
            op_$base "$@"
            exit $?
        fi
    done
    # Didnt hit a registered operation
    case "$base" in
        help)
            usage
            exit $?
            ;;
        *)
            echo "Unknown command '$base'"
            usage
            exit 1
            ;;
    esac
}


################################################################################
# Functional
################################################################################

# Take and import implementation
if [[ $# -eq 0 ]] || [ -z "$1" ]; then
    echo "Usage: $0 {script} {command}" >&2
    exit 1
fi
if [ -f "$1" ] || [ -L "$1" ]; then
    CONF_FILE="$1"
    . "$CONF_FILE"
    FALLBACK_NAME=$(basename $CONF_FILE)
    shift
elif [ -f "$(dirname $0)/ignite_$1" ] || [ -L "$(dirname $0)/ignite_$1" ]; then
    CONF_FILE="$(dirname $0)/ignite_$1"
    . "$CONF_FILE"
    FALLBACK_NAME=$(basename $CONF_FILE)
    shift
else
    echo "Ignite script does not exist" >&2
    exit 1
fi


VALID_OPERATIONS=${VALID_OPERATIONS:-()}
SOURCE_PATH=${SOURCE_PATH:-"."}

# Execute main function
main "$@"
